### ISSUE TITLE
options for E vs e 

### ISSUE THREAD

**Issue by wcpines** [andyl/vim-textobj-elixir#2]
If I recall correctly, in vim-textobj-ruby, `M` defaulted to class or module, whereas `m` had function/method scope. 

Would it be possible to add that here;  `E` defaulting to module, and `e` to function?

**Comment by andyl** [comment]
Going to forego this option, to keep it simple.  Workaround is `ggjvae` or `ggVG` instead of `vaE`.

**Comment by andyl** [comment]
There's another workaround:
- in the function `vae` (Visual Around Elixir-block)
- then expand the block `ie` (Inside Elixir-block) to get all the text inside the Module
- and you can expand the block again `ae` (Around Elixir-block) to get the `defmodule` and `end` lines...
